import type { Project } from "@/types";

export const projects: Project[] = [
  {
    title: "BAKLOG",
    category: "Local-first game library · Solo founder project",
    image: "baklog.webp",
    url: "https://baklog.app",
    stack: ["Python", "JavaScript", "Local-first", "CDP auth", "Chart.js"],
    metric: "25 fetch sources · live sync · 480 tests",
    outcome:
      "Local-first app that unifies game libraries across major storefronts on your machine.",
    featured: true,
    featuredEyebrow: "Featured · Founder project",
    caseStudySlug: "baklog",
    featuredBlurb:
      "Solo-built local-first app that unifies game libraries across Steam, Epic, GOG, PlayStation, Xbox, and more on your machine. A responsive, real-time fetch module orchestrates 25 sources with per-source freshness tracking, no cloud account required. Ownership-aware deal radar, cross-store dedupe, and a dashboard with 130+ locally computed stats.",
  },
  {
    title: "FIRST - Foundation for Ichthyosis & Related Skin Types",
    category: "Global rare-disease nonprofit",
    image: "first.webp",
    url: "https://firstskinfoundation.org/",
    stack: ["WordPress", "Gutenberg", "GenerateBlocks"],
    metric: "$2.2M research · 1,600+ patient registry",
    outcome:
      "Events, physician finder, and donation flows for a global rare-disease nonprofit.",
    caseStudySlug: "first",
  },
  {
    title: "Madishroom",
    category: "E-commerce · Shopify storefront",
    image: "madishroom.webp",
    url: "https://madishroom.com",
    stack: ["Shopify", "Liquid"],
    metric: "End-to-end owner-operator launch",
    outcome:
      "Custom Liquid theme, product flows, and conversion-focused storefront built and shipped end-to-end.",
  },
  {
    title: "Virginia G. Piper Charitable Trust",
    category: "Philanthropy · Maricopa County, AZ",
    image: "piper.webp",
    url: "https://pipertrust.org/",
    stack: ["WordPress", "ACF"],
    metric: "$764M+ AZ philanthropy",
    outcome: "Custom theme and grants experience for Arizona's largest philanthropy.",
  },
  {
    title: "Helios Education Foundation",
    category: "Annual Report Site",
    image: "helios.webp",
    url: "https://annualreports.helios.org/",
    stack: ["WordPress", "Gutenberg"],
    metric: "$350M+ over 20 years",
    outcome: "Annual report site highlighting impact across early learning and college success.",
  },
  {
    title: "Alta Uptown",
    category: "Luxury Apartments · Chandler, AZ",
    image: "uptown.webp",
    url: "https://altauptown.com/",
    stack: ["WordPress", "ACF"],
    metric: "+30–50 pt Lighthouse",
    outcome: "Greystar Alta rollout with shared multifamily theme across 100+ properties.",
  },
  {
    title: "NYX Cycle & Fitness",
    category: "Fitness · Scottsdale, AZ",
    image: "nyx.webp",
    url: "https://nyxcycle.com",
    stack: ["WordPress"],
    metric: "Brand-forward custom theme",
    outcome: "High-energy studio site with distinctive typography and class booking flows.",
  },
  {
    title: "Fionna Carlisle",
    category: "Artist Portfolio",
    image: "fionna.webp",
    url: "http://www.fionnacarlisle.com",
    stack: ["WordPress"],
    metric: "Acclaimed Scottish artist · gallery",
    outcome: "Gallery-forward portfolio for exhibitions, news, and collector outreach.",
  },
];
